"""Copilot Mode — render `agent-task.md` from experiment.yaml + experiment.md.

`hlab run` with `run.mode: copilot` calls `render_agent_task()` to produce a
clear, self-contained task for an EXTERNAL execution agent (Claude Code / Codex
/ Cursor Agent). That agent performs the runtime-specific execution and writes
`evidence/`; AHL keeps `experiment.yaml` as the source of truth.

`agent-task.md` is GENERATED and regenerated deterministically on every run — it
is NOT the source of truth. There are no timestamps and no randomness, so the
same `experiment.yaml` + `experiment.md` always produce byte-identical output.
"""
from __future__ import annotations

from pathlib import Path

from agent_harness_lab.experiment_spec import (
    ExperimentSpec,
    ExperimentSpecError,
    load_agent_runtime_spec,
    load_cases,
)
from agent_harness_lab.mdutil import is_filled, split_sections

AGENT_TASK_FILENAME = "agent-task.md"

# experiment.md section titles we surface as human context (scaffold.py authoritative).
_MD_WHY = "Why are we running this experiment?"
_MD_HUMAN_REVIEW = "What requires human review?"
_MD_INVALID = "When should the result be considered invalid or weak?"

_COLLECTION_KEYS = ("traces", "raw", "artifacts", "snapshots", "scores")
_REVIEW_KEYS = ("artifact_review", "skill_review", "memory_review", "context_review")


def _cell(text: object) -> str:
    """Safe value for a Markdown table cell: a `|` or newline in a user-controlled
    value (harness name/path/id, runtime id/spec) must not add columns or wrap rows."""
    return str(text).replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()


def _quote(text: str) -> str:
    """Render untrusted free text (question, experiment.md prose) as a blockquote.

    A user value containing a line like `## What not to do` must not be able to
    impersonate one of AHL's authoritative section headers in the generated task;
    inside a blockquote, `> ## ...` is quoted text, not a header. Empty -> ''. """
    lines = str(text).splitlines() or [""]
    return "\n".join("> " + ln for ln in lines)


def _md_section(exp_dir: Path, title: str) -> str | None:
    """Return a filled experiment.md section body, or None if absent/placeholder."""
    md = exp_dir / "experiment.md"
    if not md.exists():
        return None
    body = split_sections(md.read_text(encoding="utf-8")).get(title, "")
    return body if is_filled(body) else None


def _connector_for(exp_dir: Path, spec_rel: object) -> str:
    """Resolve a runtime spec's connector type for display (never raises)."""
    if not isinstance(spec_rel, str) or not spec_rel:
        return "(unset)"
    sp = exp_dir / spec_rel
    if not sp.exists():
        return "(missing spec)"
    try:
        return load_agent_runtime_spec(sp).connector_type or "(unset)"
    except ExperimentSpecError:
        return "(unreadable)"


def _runtime_artifacts(exp_dir: Path, spec_rel: object) -> list[dict]:
    """Declared artifacts.collect[] rules for a runtime spec (never raises)."""
    if not isinstance(spec_rel, str) or not spec_rel:
        return []
    sp = exp_dir / spec_rel
    if not sp.exists():
        return []
    try:
        return load_agent_runtime_spec(sp).artifacts
    except ExperimentSpecError:
        return []


def _case_count(exp_dir: Path, spec: ExperimentSpec) -> int:
    if not (spec.cases_root and spec.cases_files):
        return -1
    try:
        return len(load_cases(exp_dir / spec.cases_root, spec.cases_files))
    except ExperimentSpecError:
        return -1


def _workspace_methods(exp_dir: Path) -> list[str]:
    """Workspace-level Evaluation Methods (evaluation-methods/*.md), if present.

    The workspace root is two levels up from experiments/<exp>/."""
    md_dir = exp_dir.parent.parent / "evaluation-methods"
    if not md_dir.is_dir():
        return []
    return sorted(p.stem for p in md_dir.glob("*.md"))


def render_agent_task(exp_dir: Path, spec: ExperimentSpec) -> str:
    """Build the agent-task.md content (deterministic; no timestamps)."""
    eid = spec.id or exp_dir.name
    L: list[str] = []

    # --- header: generated, not source of truth -----------------------------
    L += [
        f"# Agent Task — {eid}",
        "",
        "> GENERATED by `hlab run` from `experiment.yaml` (machine source of truth)",
        "> and `experiment.md` (human plan). **This file is not the source of truth.**",
        "> To change the experiment, edit `experiment.yaml` / `experiment.md` and re-run",
        "> `hlab run` — this file is overwritten deterministically each time.",
        "",
        "You are the **external execution agent**. Perform the runtime-specific",
        "execution described below and write evidence into the locations given.",
        "AHL prepared this task; AHL did not run any Agent Runtime for you.",
        "",
    ]

    # --- 1. Experiment question ---------------------------------------------
    L += ["## Experiment question", "",
          (_quote(spec.question) if spec.question else "(unset — fix experiment.yaml `question`)"), ""]
    why = _md_section(exp_dir, _MD_WHY)
    if why:
        L += ["Why it matters (from experiment.md):", "", _quote(why), ""]

    # --- 2. Goal reference ---------------------------------------------------
    L += [
        "## Goal reference",
        "",
        f"This experiment serves the workspace goal at `{spec.goal_ref or '(unset)'}`.",
        "Read it before you start so the run stays tied to the long-term objective.",
        "",
    ]

    # --- 3. Harnesses --------------------------------------------------------
    L += ["## Harnesses", "", "What is being compared. Apply each harness to its Agent Runtime exactly as configured.", ""]
    if spec.harnesses:
        L += ["| id | name | path |", "|----|------|------|"]
        for h in spec.harnesses:
            L.append(f"| {_cell(h.id)} | {_cell(h.name)} | {_cell(h.path)} |")
    else:
        L.append("(no harnesses declared — fix experiment.yaml `harnesses`)")
    L.append("")

    # --- 4. Agent Runtimes ---------------------------------------------------
    L += ["## Agent Runtimes", "", "The real environment each harness runs in. Drive each runtime via its connector.", ""]
    if spec.agent_runtimes:
        L += ["| id | harness | spec | connector |", "|----|---------|------|-----------|"]
        for r in spec.agent_runtimes:
            L.append(f"| {_cell(r.id)} | {_cell(r.harness)} | {_cell(r.spec)} | {_cell(_connector_for(exp_dir, r.spec))} |")
    else:
        L.append("(no agent runtimes declared — fix experiment.yaml `agent_runtimes`)")
    # expected artifacts each runtime may produce (from agent-runtimes/*.yaml)
    _art_lines: list[str] = []
    for r in spec.agent_runtimes:
        for a in _runtime_artifacts(exp_dir, r.spec):
            if not isinstance(a, dict):
                continue
            req = " (required)" if a.get("required") else ""
            kind = f" [{_cell(a.get('kind'))}]" if a.get("kind") else ""
            _art_lines.append(
                f"- {_cell(r.id)} → `{_cell(a.get('id'))}`{kind}{req}: glob `{_cell(a.get('glob'))}`")
    if _art_lines:
        L += ["", "**Expected artifacts** — collect each match and place it under "
              "`evidence/artifacts/<runtime>/` (AHL does not specify a destination path; "
              "you archive it there):"]
        L += _art_lines
    L.append("")

    # --- 5. Cases ------------------------------------------------------------
    n = _case_count(exp_dir, spec)
    files = ", ".join(spec.cases_files) if spec.cases_files else "(none)"
    L += [
        "## Cases",
        "",
        f"Run **every** case against **each** Agent Runtime above.",
        f"- root: `{spec.cases_root or '(unset)'}`",
        f"- files: {files}",
        f"- case count: {n if n >= 0 else '(unreadable — fix cases)'}",
        "",
    ]

    # --- 5b. Simulator (optional) -------------------------------------------
    if spec.simulator is not None and spec.simulator.type:
        sraw = spec.simulator.raw if isinstance(spec.simulator.raw, dict) else {}
        st = spec.simulator.type
        L += ["## Simulator", "",
              f"The user side of each case is driven by a **{_cell(st)}** simulator."]
        if st == "script":
            L.append(f"- script: `{_cell(sraw.get('script'))}` — run it to produce each user turn.")
        elif st == "scripted":
            _mt = sraw.get("max_turns")
            pb = sraw.get("playbook")
            L.append(f"- playbook: `{_cell(pb)}` · max_turns: "
                     f"{_cell(_mt) if _mt is not None else '(unset)'}")
            L.append(f"- User turns are driven deterministically by the playbook file "
                     f"`{_cell(pb)}`. Issue the playbook's follow-up messages in order "
                     f"(one per turn, turn 1 onward); stop when the sequence ends or "
                     f"max_turns is reached.")
        elif st == "role_play":
            _mt = sraw.get("max_turns")
            L.append(f"- actor: {_cell(sraw.get('actor'))} · max_turns: "
                     f"{_cell(_mt) if _mt is not None else '(unset)'} · policy: `{_cell(sraw.get('policy'))}`")
            L.append("- In Copilot Mode you (the external agent) play the actor per the "
                     "policy file (four sections: Persona / Background / Strategy / Stop). "
                     "In Auto Mode (`hlab run` with `AHL_SIM_*` configured), role_play is "
                     "executed automatically by the simulator engine.")
        else:  # single_turn
            L.append("- single_turn: send each case input once; no multi-turn user simulation.")
        L.append("")

    # --- 6. Evaluation requirements (three layers) --------------------------
    L += ["## Evaluation requirements", ""]
    # layer 1: workspace-level Evaluation Methods (recipes in evaluation-methods/)
    _methods = _workspace_methods(exp_dir)
    if _methods:
        L.append(f"Evaluation Methods available at the workspace level: {', '.join(_methods)}.")
    # layer 2: experiment-local evaluator instances
    if spec.evaluators:
        L += ["", "Experiment evaluators (configured instances):",
              "| id | method | script / rubric |", "|----|--------|-----------------|"]
        for ev in spec.evaluators:
            ref = ev.script or ev.rubric or "(none)"
            L.append(f"| {_cell(ev.id)} | {_cell(ev.method)} | {_cell(ref)} |")
    elif spec.evaluation_methods:
        L += ["", "Evaluation methods configured (shorthand): "
              + ", ".join(_cell(m) for m in spec.evaluation_methods)]
    else:
        L += ["", "(no evaluators configured — fix experiment.yaml `evaluation.evaluators`)"]
    # layer 3: experiment-local tracks (grouping + the evidence each needs)
    if spec.tracks:
        L += ["", "Experiment evaluation tracks (experiment-local groupings):"]
        for tr in spec.tracks:
            q = f" — {_cell(tr.question)}" if tr.question else ""
            L.append(f"- **{_cell(tr.id)}**{q}")
            L.append(f"  - evaluators: "
                     f"{', '.join(_cell(x) for x in tr.evaluators) if tr.evaluators else '(none)'}")
            L.append(f"  - evidence needed: "
                     f"{', '.join(_cell(x) for x in tr.evidence) if tr.evidence else '(none)'}")
    else:
        L += ["", "(no evaluation tracks defined — report grouping will be weak)"]
    L += [
        "",
        f"Evaluation design lives under `{spec.evaluation_root or 'evaluation/'}`. "
        "Tracks are **experiment-local** and do NOT replace evidence — you must still "
        "write the evidence each track needs. Do not score, rank, or conclude: AHL runs "
        "evaluation later; your job is to make the evidence sufficient for these "
        "evaluators and tracks.",
        "",
    ]

    # --- 7. Evidence collection requirements --------------------------------
    coll = spec.collection if isinstance(spec.collection, dict) else {}
    on = [k for k in _COLLECTION_KEYS if coll.get(k)]
    off = [k for k in _COLLECTION_KEYS if k in coll and not coll.get(k)]
    insp = spec.inspection if isinstance(spec.inspection, dict) else {}
    reviews = [k for k in _REVIEW_KEYS if insp.get(k)]
    checks = [c for c in (insp.get("issue_checks") or []) if isinstance(c, str)]
    L += ["## Evidence collection requirements", ""]
    L.append("Collect exactly the evidence configured — no more, no less:")
    L.append(f"- collect: {', '.join(on) if on else '(none configured — fix `collection`)'}")
    if off:
        L.append(f"- do NOT collect (explicitly off): {', '.join(off)}")
    if reviews:
        L.append(f"- evidence must support these human reviews: {', '.join(reviews)}")
    if checks:
        L.append(f"- inspection will run these checks, so the evidence must let them pass: {', '.join(checks)}")
    L.append("")

    # --- 8. Required output locations ---------------------------------------
    L += [
        "## Required output locations",
        "",
        "Write all evidence under the experiment's `evidence/` tree (paths relative to",
        "this experiment directory). Create only what collection requires:",
    ]
    _LOC = {
        "traces": "evidence/traces/      — one trace record per case/runtime",
        "raw": "evidence/raw/         — raw stdout/stderr per runtime",
        "artifacts": "evidence/artifacts/   — produced artifacts per runtime/case",
        "snapshots": "evidence/snapshots/   — state snapshots (if applicable)",
        "scores": "evidence/scores/      — score material (filled at evaluation)",
    }
    for k in _COLLECTION_KEYS:
        if coll.get(k):
            L.append(f"- `{_LOC[k]}`")
    L += [
        "- `evidence/issues.jsonl` — one JSON object per problem encountered",
        "- `evidence/inspections/`  — inspection output (AHL may write here)",
        "",
        "Do not write experiment outputs anywhere else (not `reports/`, not the repo root).",
        "",
    ]

    # --- 9. Stop conditions --------------------------------------------------
    L += [
        "## Stop conditions",
        "",
        "Stop when any of these holds — do not run open-endedly:",
        "- every case has been run against every Agent Runtime and its evidence written; or",
        "- a connector or case fails unrecoverably: record the failure in "
        "`evidence/issues.jsonl` and stop that runtime (do not retry indefinitely); or",
        "- you cannot proceed without changing `experiment.yaml` — stop and report instead.",
    ]
    invalid = _md_section(exp_dir, _MD_INVALID)
    if invalid:
        L += ["", "Treat the result as invalid/weak under these human-defined conditions (from experiment.md):", "", _quote(invalid)]
    L.append("")

    # --- 10. What not to do --------------------------------------------------
    L += [
        "## What not to do",
        "",
        "- Do not treat this file as the source of truth, and do not edit "
        "`experiment.yaml` to make the run pass.",
        "- Do not fabricate, infer, or silently drop evidence — capture exactly what each "
        "runtime produced; a missing result is an issue, not an omission.",
        "- Do not change the harnesses or Agent Runtimes, or connect to anything not "
        "declared in `agent-runtimes/`.",
        "- Do not score, rank, or conclude — evaluation is a later AHL step and the final "
        "conclusion is the human's (`conclusion.md`).",
        "- Do not collect evidence that `collection` turned off.",
        "",
    ]
    human_review = _md_section(exp_dir, _MD_HUMAN_REVIEW)
    if human_review:
        L += ["Reserved for human review (do not delegate or pre-empt these):", "", _quote(human_review), ""]

    # --- 11. Required final handoff format ----------------------------------
    L += [
        "## Required final handoff format",
        "",
        "When done, return this block verbatim (filled in) so AHL/the human can pick up:",
        "",
        "```",
        f"experiment: {eid}",
        "cases run:  <done>/<total> per runtime (e.g. runtime-a 5/5, runtime-b 5/5)",
        "evidence written:",
        "  - evidence/traces/     <yes/no + count>",
        "  - evidence/raw/        <yes/no>",
        "  - evidence/artifacts/  <yes/no + count>",
        "  - evidence/issues.jsonl <N issues>",
        "blocking problems: <none | short list>",
        "ready for: hlab status " + eid + "  (then inspection / evaluation)",
        "```",
        "",
        "Do not write a conclusion — recording the conclusion is the human's job in "
        "`conclusion.md`.",
        "",
    ]

    return "\n".join(L) + "\n"


def write_agent_task(exp_dir: Path, spec: ExperimentSpec) -> Path:
    """Render and (over)write agent-task.md. Returns the path written."""
    target = exp_dir / AGENT_TASK_FILENAME
    target.write_text(render_agent_task(exp_dir, spec), encoding="utf-8")
    return target
